version: 2

registries:
  gar:
    type: docker-registry
    url: europe-north1-docker.pkg.dev

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    registries:
      - gar
    directory: "/"
    schedule:
      interval: "daily"
