apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: nada
  name: dataobs-soda-nada
  namespace: nada
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/nada/nada-soda:2025.05.20-10.43-22d8a2c
  accessPolicy:
    outbound:
      rules:
        - application: nada-soda
          namespace: nada
  env:
    - name: SODA_CONFIG
      value: /var/run/configmaps/soda-config/config.yaml
    - name: SODA_CHECKS_FOLDER
      value: /var/run/configmaps/soda-checks
    - name: SLACK_CHANNEL
      value: "#soda-test"
    - name: NOTIFY_OK_SCAN_STATUS
      value: "true"
  schedule: '15 11 * * *'
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backoffLimit: 1
  concurrencyPolicy: Forbid
  filesFrom:
    - configmap: soda-checks
    - configmap: soda-config
  gcp:
    permissions:
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: nada-prod-6977
      role: roles/bigquery.readSessionUser
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: nada-prod-6977
      role: roles/bigquery.dataViewer
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: nada-prod-6977
      role: roles/bigquery.jobUser
