apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: nada
data:
  platform_users.yaml: |
    checks for target_group:
      - row_count > 0 # Bør ikke slå ut
      - missing_count(team_id) = 0 # Bør slå ut
      - freshness(dato) < 1d # Bør også slå ut
      - schema:
          name: Find forbidden, missing, or wrong type
          warn:
            when required column missing: [team_id, naisteams]