apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: nada
data:
  platform_users.yaml: |
    checks for target_group:
      - row_count > 0 # Bør ikke slå ut
      - missing_count(team_id) = 0 # Bør slå ut
      - freshness(dato) < 1d # Bør også slå ut
      - schema:
          name: Find forbidden, missing, or wrong type
          warn:
            when required column missing: [team_id, naisteams]
    checks for team_metrics:
      - freshness(dato) <1d # Bør funke
      - row_count > 100000 # Bør slå ut
  dataproducts.yaml: |
    checks for contact_point: # Sjekker referential integrity
      - values in (id) must exist in dataproducts(dataset_id) # Denne bør feile    
    
    checks for datastories_materialized:
      - row_count > 0 # Denne bør funke

