apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: nada
data:
  dataproducts.yaml: |
    checks for dataproducts:
      - missing_count(id) = 0 # Bør ikke slå ut
      - missing_percent(type) < 50 %
    
      # Eksempler på egendefinerte sjekker
      - number_of_dataproducts >= 1: # Kan bruke common table expressions -> Det du har i with-clause i SQL
          number_of_dataproducts expression: count(distinct id)
          name: "Sjekker om vi har flere enn ett dataprodukt"
      - number_of_dataproducts_sql >= 1: # Kan gjøre tilsvarende med SQL au
          number_of_dataproducts_sql query: |
            SELECT COUNT(distinct id)
            FROM dataproducts
          name: "Sjekker om vi har flere enn ett dataprodukt, men med SQL"

