apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks-contracts
  namespace: nada
data:
  dataproducts.yaml: |
    dataset: dataproducts/nada-prod-6977/dataproducts/dataproducts

    checks:
      - row_count:
          threshold:
            must_be_greater_than_or_equal_to: 1

    columns:
      - name: dataproduct_id
        checks:
          - missing:
      - name: pii
        checks:
          - missing:
              threshold:
                metric: percent
                must_be_less_than: 50

  classification_dataset.yaml: |
    dataset: dataproducts/nada-prod-6977/dataproducts/classification_dataset

    checks:
      - row_count:
          threshold:
            must_be_greater_than_or_equal_to: 1

    columns:
      - name: dataproduct_id
        checks:
          - duplicate:
