name: Update Soda Image Tag
on: 
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile.dummy'
      - '.github/workflows/bump_soda_image.yaml'

permissions:
  contents: write
  actions: write

jobs:
  deploy:
    name: Update Soda Image Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Commit tag changes
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          newtag=$(awk -F "FROM ghcr.io/navikt/nada-soda/soda:" '{print $2}' Dockerfile.dummy)
          sed -i "s|image: .*|image: europe-north1-docker.pkg.dev/nais-management-233d/nada/nada-soda:${newtag}|g" .nais/naisjob.yaml
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git add .nais/naisjob.yaml
          git commit -m "Updated Soda image tag to ${newtag}"
          git push
