name: Update Soda Image Tag
on: 
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile.dummy'
      - 'Dockerfile.dummy-contracts'

permissions:
  contents: write
  actions: write

jobs:
  update-soda:
    name: Update Soda Image Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Commit tag changes
        run: |
          newtag=$(awk -F "FROM ghcr.io/navikt/nada-soda/soda:" '{print $2}' Dockerfile.dummy)
          sed -i "s|image: .*nada-soda:.*|image: europe-north1-docker.pkg.dev/nais-management-233d/nada/nada-soda:${newtag}|g" .nais/dev/soda/naisjob.yaml .nais/prod/soda/naisjob.yaml

          newtagcontracts=$(awk -F "FROM ghcr.io/navikt/nada-soda/soda-contracts:" '{print $2}' Dockerfile.dummy-contracts)
          sed -i "s|image: .*nada-soda-contracts:.*|image: europe-north1-docker.pkg.dev/nais-management-233d/nada/nada-soda-contracts:${newtagcontracts}|g" .nais/dev/soda-contracts/naisjob.yaml .nais/prod/soda-contracts/naisjob.yaml

          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git add .nais/dev/soda/naisjob.yaml .nais/prod/soda/naisjob.yaml .nais/dev/soda-contracts/naisjob.yaml .nais/prod/soda-contracts/naisjob.yaml
          git diff --staged --quiet || git commit -m "Updated Soda image tags"
          git push
